import "server-only";
import fs from "node:fs";
import path from "node:path";

/**
 * Server-only loader for data/evolution.json (ADR-018). The file is generated by
 * scripts/extract-evolution.mjs and is never edited by hand. A missing or invalid
 * file degrades to an empty archive instead of failing the page.
 */

export type EvolutionEventType =
  | "adr_added"
  | "adr_superseded"
  | "product_registered"
  | "product_status_changed"
  | "route_added"
  | "route_removed"
  | "milestone_shipped"
  | "pr_merged"
  | "registry_changed"
  | "security_fix"
  | "scene_registered";

export type EvolutionEvent = {
  id: string;
  type: EvolutionEventType;
  date: string;
  title: string;
  summary: string;
  references: string[];
  division: string | null;
  product: string | null;
  outcome: string;
};

export type EvolutionStats = {
  adrs_total?: number;
  adrs_superseded?: number;
  products_total?: number;
  products_by_status?: Record<string, number>;
  scenes_total?: number;
  milestones_shipped?: number;
  prs_merged?: number;
  verified_capabilities?: number;
};

export type Evolution = {
  events: EvolutionEvent[];
  stats: EvolutionStats;
  generated_at: string | null;
};

const EMPTY: Evolution = { events: [], stats: {}, generated_at: null };

export const EVOLUTION_FILE = path.join(process.cwd(), "data", "evolution.json");

export function loadEvolution(): Evolution {
  try {
    const parsed = JSON.parse(fs.readFileSync(EVOLUTION_FILE, "utf8")) as Partial<Evolution>;
    if (!parsed || !Array.isArray(parsed.events) || typeof parsed.stats !== "object" || !parsed.stats) {
      console.warn("evolution: data/evolution.json has an unexpected shape; showing an empty archive.");
      return EMPTY;
    }
    return {
      events: parsed.events,
      stats: parsed.stats,
      generated_at: typeof parsed.generated_at === "string" ? parsed.generated_at : null,
    };
  } catch (error) {
    console.warn(`evolution: cannot read data/evolution.json (${(error as Error).message}).`);
    return EMPTY;
  }
}
